name: TheDoctorReborn
description: Regenerate 12 times as a Time Lord.
version: 0.3.2
api-version: 1.20
load: STARTUP
author: leothawne
website: https://www.spigotmc.org/resources/60429
url: https://www.spigotmc.org/resources/60429
main: io.github.leothawne.TheDoctorReborn.TheDoctorReborn
database: true
commands:
    reborn:
        description: A The Doctor Reborn command.
        aliases: [rb]
        usage: /<command>
    rebornadmin:
        description: A The Doctor Reborn command.
        aliases: [rba]
        usage: /<command>
permissions:
    TheDoctorReborn.use:
        description: A The Doctor Reborn permission node.
        default: true
    TheDoctorReborn.admin:
        description: A The Doctor Reborn permission node.
        default: op